LOCAL_FFTW3_PATH := $(call my-dir)

### fftw3
LOCAL_PATH := $(LOCAL_FFTW3_PATH)

include $(CLEAR_VARS)

LOCAL_MODULE := libfftw3

LOCAL_SRC_FILES := lib/$(TARGET_ARCH_ABI)/libfftw3.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include

include $(PREBUILT_STATIC_LIBRARY)
