package com.mybraintech.sdk.core.model

/**
 * TODO: specify error code for all implement.
 */
enum class MBTErrorCode(val code: Int) {
    BLUETOOTH_DISABLED(1011),
    DEVICE_CONNECTED_ALREADY(1013),
    FAILED_TO_CONNECTED_TO_DEVICE(1015),
    NO_CONNECTED_DEVICE_TO_CONNECT(1017),
    NO_CONNECTED_DEVICE_TO_DISCONNECT(1029),
    BLE_SIGNAL_COULD_NOT_BE_READY(1031),
    WRONG_DEVICE_QR_CODE(1019),
    NO_BLE_DEVICE_FOUND(1021),
    NO_AUDIO_DEVICE_FOUND(1027),
    FAILED_TO_CONNECT_TO_BLE_DEVICE(1023),
    FAILED_TO_CONNECT_TO_AUDIO_DEVICE(1025),
}