package model;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import core.recording.metadata.MelomindExerciseSource;
import core.recording.metadata.MelomindExerciseType;

import static core.recording.metadata.MelomindExerciseType.DEFAULT;
import static core.recording.metadata.SessionMetaDataKt.RAWDATA;

/**
 * Created by manon on 19/10/16.
 */

/**
 * Class for informations about a new recording. It has a unique id, which is generated by the application then sent
 * to the server in the JSON file.
 * Id is unique for an acquisition session (ie calibration + session for melomind)
 * It also has a recordingType variable which indicates the global settings of this session
 */
@Keep
public class RecordInfo {

    private String recordId;
    private  RecordingType recordingType;

    public RecordInfo(){}

    public RecordInfo(@NonNull String recordId){
        this.recordId = recordId;
        this.recordingType = new RecordingType();
    }

    public RecordInfo(@NonNull String recordId, @NonNull RecordingType recordingType){
        this.recordId = recordId;
        this.recordingType = recordingType;
    }

    public String getRecordId() {
        return recordId;
    }

    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    public RecordingType getRecordingType() {
        return recordingType;
    }

    public void setRecordingType(RecordingType recordingType) {
        this.recordingType = recordingType;
    }

    public RecordInfo setSPVersion(String SPVersion) {
        this.recordingType.setSPVersion(SPVersion);
        return this;
    }

    /**
     * Inner class for recording type.
     */
    @Keep
    public class RecordingType{
        private String recordType;
        private String spVersion;
        private MelomindExerciseSource source;
        private MelomindExerciseType exerciseType;

        public RecordingType(){
            this.exerciseType = DEFAULT;
            this.source = MelomindExerciseSource.DEFAULT;
            this.recordType = RAWDATA;
        }

        public RecordingType(@NonNull String recordType, @NonNull String spVersion, @NonNull MelomindExerciseSource dataSource, @NonNull MelomindExerciseType exerciseType){
            this.exerciseType = exerciseType;
            this.source = dataSource;
            this.spVersion = spVersion;
            this.recordType = recordType;
        }

        public String getRecordType() {
            return recordType;
        }

        public void setRecordType(String recordType) {
            this.recordType = recordType;
        }

        public String getSPVersion() {
            return spVersion;
        }

        public void setSPVersion(String SPVersion) {
            this.spVersion = SPVersion;
        }

        public MelomindExerciseSource getSource() {
            return source;
        }

        public void setSource(MelomindExerciseSource source) {
            this.source = source;
        }

        public MelomindExerciseType getExerciseType() {
            return exerciseType;
        }

        public void setExerciseType(MelomindExerciseType exerciseType) {
            this.exerciseType = exerciseType;
        }

        @Override
        public String toString() {
            return "RecordingType{" +
                    "recordType=" + recordType +
                    ", spVersion='" + spVersion + '\'' +
                    ", source=" + source +
                    ", exerciseType=" + exerciseType +
                    '}';
        }
    }

    @Override
    public String toString() {
        return "RecordInfo{" +
                "recordId='" + recordId + '\'' +
                ", recordingType=" + recordingType +
                '}';
    }
}




