/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mybraintech_com_mbtsdk_core_signalprocessing_MBTCalibrator */

#ifndef _Included_core_eeg_signalprocessing_MBTCalibrator
#define _Included_core_eeg_signalprocessing_MBTCalibrator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_eeg_signalprocessing_MBTCalibrator
 * Method:    nativeCalibrate
 * Signature: (II[[D[[D)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_core_eeg_signalprocessing_MBTCalibrator_nativeCalibrate
  (JNIEnv *, jclass, jint, jint, jobjectArray, jobjectArray);

JNIEXPORT jobject JNICALL Java_core_eeg_signalprocessing_MBTCalibrator_nativeCalibrateNew
        (JNIEnv *env, jclass caller, jint samprate, jint packetLength, jint calibLength, jint smoothingDuration, jobjectArray qt_matrix, jobjectArray sig_matrix);

#ifdef __cplusplus
}
#endif
#endif
