/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_eeg_signalprocessing_MBTSignalQualityChecker */

#ifndef _Included_core_eeg_signalprocessing_MBTSignalQualityChecker
#define _Included_core_eeg_signalprocessing_MBTSignalQualityChecker

extern "C" {

/*
 * Class:     core_eeg_signalprocessing_MBTSignalQualityChecker
 * Method:    nativeComputeQualities
 * Signature: ([[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL
Java_core_eeg_signalprocessing_MBTSignalQualityChecker_nativeComputeQualities
  (JNIEnv *, jclass, jobjectArray, jint, jint);


JNIEXPORT jfloatArray JNICALL
Java_core_eeg_signalprocessing_MBTSignalQualityChecker_nativeComputeQualityCheckerNew(JNIEnv *env,
                                                                                     jclass type,
                                                                                     jobjectArray matrix,
                                                                                     jint samprate,
                                                                                     jint packetLength);

JNIEXPORT jobjectArray JNICALL
Java_core_eeg_signalprocessing_MBTSignalQualityChecker_nativeGetModifiedInputData(JNIEnv *env,
                                                                                         jclass type);

JNIEXPORT jstring JNICALL
Java_core_eeg_signalprocessing_MBTSignalQualityChecker_nativeInitQualityChecker(JNIEnv *env,
                                                                               jclass type);

JNIEXPORT void JNICALL
Java_core_eeg_signalprocessing_MBTSignalQualityChecker_nativeDeinitQualityChecker(JNIEnv *env,
                                                                                 jclass type);


JNIEXPORT jobjectArray JNICALL
Java_core_eeg_signalprocessing_MBTSignalQualityChecker_nativeGetFeatures(JNIEnv *env, jclass type);


}
#endif
