///* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_eeg_signalprocessing_MBTSignalQualityChecker */

#ifndef _Included_core_eeg_signalprocessing_MBTSignalQualityChecker
#define _Included_core_eeg_signalprocessing_MBTSignalQualityChecker



#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL
Java_core_eeg_signalprocessing_MBTComputeStatistics_nativeComputeStatistics(JNIEnv *env, jclass type,
                                                                           jint sampRate,
                                                                           jint packetLength,
                                                                           jfloatArray inputData_);

JNIEXPORT jobject JNICALL
Java_core_eeg_signalprocessing_MBTComputeStatistics_nativeComputeStatisticsSNR(JNIEnv *env, jclass type,
                                                                          jfloat threshold,
                                                                          jint size,
                                                                          jfloatArray inputData_);

#ifdef __cplusplus
}
#endif
#endif
