/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class modules_signalprocessing_MBTSignalQualityChecker */

#ifndef _Included_mybraintech_com_mbtsdk_core_signalprocessing_MBTSignalQualityChecker
#define _Included_mybraintech_com_mbtsdk_core_signalprocessing_MBTSignalQualityChecker

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     modules_signalprocessing_MBTSignalQualityChecker
 * Method:    nativeComputeQualities
 * Signature: ([[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_mybraintech_com_mbtsdk_core_signalprocessing_MBTSignalQualityChecker_nativeComputeQualities
  (JNIEnv *, jclass, jobjectArray, jint, jint);


JNIEXPORT jfloatArray JNICALL
        Java_mybraintech_com_mbtsdk_core_signalprocessing_MBTSignalQualityChecker_nativeComputeQualityCheckerNew(JNIEnv *env,
                                                                                     jclass type,
                                                                                     jobjectArray matrix,
                                                                                     jint samprate,
                                                                                     jint packetLength);

JNIEXPORT jobjectArray JNICALL
        Java_mybraintech_com_mbtsdk_core_signalprocessing_MBTSignalQualityChecker_nativeGetModifiedInputData(JNIEnv *env,
                                                                                         jclass type);

JNIEXPORT jstring JNICALL
Java_mybraintech_com_mbtsdk_core_signalprocessing_MBTSignalQualityChecker_nativeInitQualityChecker(JNIEnv *env,
                                                                               jclass type);

JNIEXPORT void JNICALL
Java_mybraintech_com_mbtsdk_core_signalprocessing_MBTSignalQualityChecker_nativeDeinitQualityChecker(JNIEnv *env,
                                                                                 jclass type);

#ifdef __cplusplus
}
#endif
#endif
