/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mybraintech_com_mbtsdk_core_signalprocessing_MBTComputeRelaxIndex */

#ifndef _Included_mybraintech_com_mbtsdk_core_signalprocessing_MBTComputeRelaxIndex
#define _Included_mybraintech_com_mbtsdk_core_signalprocessing_MBTComputeRelaxIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mybraintech_com_mbtsdk_core_signalprocessing_MBTComputeRelaxIndex
 * Method:    nativeComputeRelaxIndex
 * Signature: (ILmodules/signalprocessing/MBTCalibrationParameters;[[D[[D)D
 */

JNIEXPORT jfloat JNICALL
Java_mybraintech_com_mbtsdk_core_signalprocessing_MBTComputeRelaxIndex_nativeComputeRelaxIndex(JNIEnv *env,
                                                                              jclass type,
                                                                              jint samprate,
                                                                              jobject parameters,
                                                                              jobjectArray qualities,
                                                                              jobjectArray matrix);

JNIEXPORT void JNICALL
Java_mybraintech_com_mbtsdk_core_signalprocessing_MBTComputeRelaxIndex_nativeReinitRelaxIndexVariables(JNIEnv *env,
                                                                                   jclass type);


JNIEXPORT jobject JNICALL
Java_mybraintech_com_mbtsdk_core_signalprocessing_MBTComputeRelaxIndex_nativeGetSessionMetadata(JNIEnv *env,
                                                                            jclass type);


#ifdef __cplusplus
}
#endif
#endif
