///* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mybraintech_com_mbtsdk_modules_signalprocessing_MBTSignalQualityChecker */

#ifndef _Included_mybraintech_com_mbtsdk_modules_signalprocessing_MBTSignalQualityChecker
#define _Included_mybraintech_com_mbtsdk_modules_signalprocessing_MBTSignalQualityChecker



#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jobject JNICALL
Java_com_mybraintech_android_jnibrainbox_ComputeStatistics_nativeComputeStatisticsSNR(JNIEnv *env, jclass type,
                                                                                      jfloat threshold,
                                                                                      jint size,
                                                                                      jfloatArray inputData_);

#ifdef __cplusplus
}
#endif
#endif
