/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mybraintech_android_jnibrainbox_Calibration */

#ifndef _Included_com_mybraintech_android_jnibrainbox_Calibration
#define _Included_com_mybraintech_android_jnibrainbox_Calibration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mybraintech_android_jnibrainbox_Calibration
 * Method:    new_calibration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mybraintech_android_jnibrainbox_Calibration_new_1calibration
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mybraintech_android_jnibrainbox_Calibration
 * Method:    destroy_calibration
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mybraintech_android_jnibrainbox_Calibration_destroy_1calibration
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_Calibration
 * Method:    compute_calibration
 * Signature: ([[F[[F)I
 */
JNIEXPORT jint JNICALL Java_com_mybraintech_android_jnibrainbox_Calibration_compute_1calibration
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_mybraintech_android_jnibrainbox_Calibration
 * Method:    get_rms
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_Calibration_get_1rms
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_Calibration
 * Method:    get_relative_rms
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_Calibration_get_1relative_1rms
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_Calibration
 * Method:    get_relative_rms
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_Calibration_get_1smoothed_1rms
        (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_Calibration
 * Method:    get_hist_freq
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_Calibration_get_1hist_1freq
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_Calibration
 * Method:    get_iaf
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_Calibration_get_1iaf
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
