/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mybraintech_android_jnibrainbox_RelaxIndex */

#ifndef _Included_com_mybraintech_android_jnibrainbox_RelaxIndex
#define _Included_com_mybraintech_android_jnibrainbox_RelaxIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    new_relax_index
 * Signature: (I[[FFF)V
 */
JNIEXPORT void JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_new_1relax_1index
  (JNIEnv *, jobject, jint, jfloatArray, jfloat, jfloat);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    destroy_relax_index
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_destroy_1relax_1index
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    compute
 * Signature: ([[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_compute
  (JNIEnv *, jobject, jobjectArray, jfloatArray);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    end_session
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_end_1session
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_mean_alpha_power
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1mean_1alpha_1power
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_mean_relative_alpha_power
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1mean_1relative_1alpha_1power
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_confidence
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1confidence
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_volums
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1volums
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_alpha_powers
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1alpha_1powers
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_relative_alpha_powers
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1relative_1alpha_1powers
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_qualities
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1qualities
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_past_relax_index
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1past_1relax_1index
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_RelaxIndex
 * Method:    get_smoothed_relax_index
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_RelaxIndex_get_1smoothed_1relax_1index
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
