/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mybraintech_android_jnibrainbox_QualityChecker */

#ifndef _Included_com_mybraintech_android_jnibrainbox_QualityChecker
#define _Included_com_mybraintech_android_jnibrainbox_QualityChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mybraintech_android_jnibrainbox_QualityChecker
 * Method:    new_quality_checker
 * Signature: ()J
 */
JNIEXPORT void JNICALL Java_com_mybraintech_android_jnibrainbox_QualityChecker_new_1quality_1checker
  (JNIEnv *, jobject , jint);

/*
 * Class:     com_mybraintech_android_jnibrainbox_QualityChecker
 * Method:    destroy_quality_checker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mybraintech_android_jnibrainbox_QualityChecker_destroy_1quality_1checker
  (JNIEnv *, jobject);

/*
 * Class:     com_mybraintech_android_jnibrainbox_QualityChecker
 * Method:    compute_quality_checker
 * Signature: ([[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mybraintech_android_jnibrainbox_QualityChecker_compute_1quality_1checker
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
