package core.eeg.storage;

import android.support.annotation.Keep;

@Keep
public enum Feature {

    MEDIAN,
    MEAN,
    VARIANCE,
    VRMS,
    VPP,
    SKEWNESS,
    KURTOSIS,
    INTEGRATED_EEG,
    MEAN_ABSOLUTE_VALUE,
    SIMPLE_SQUARE_INTEGRAL,
    V_ORDER_2_AND_3,
    LOG_DETECTOR,
    AVERAGE_AMPLITUDE_CHANGE,
    DIFFERENCE_ABSOLUTE_STANDARD_DEVIATION,
    NUMBER_OF_MAXIMA_AND_MINIMA,
    MOBILITY_HJORTH_PARAMETER,
    COMPLEXITY_HJORTH_PARAMETER,
    ZERO_CROSSING_RATE,
    ZERO_CROSSING_RATE_1ST_DERIVATIVE,
    ZERO_CROSSING_RATE_2ND_DERIVATIVE,
    VARIANCE_1ST_DERIVATIVE,
    VARIANCE_2ND_DERIVATIVE,
    NON_LINEAR_ENERGY,

    DELTA_MAXIMUM,
    DELTA_KURTOSIS,
    DELTA_STANDARD_DEVIATION,
    DELTA_SKEWNESS,

    THETA_MAXIMUM,
    THETA_KURTOSIS,
    THETA_STANDARD_DEVIATION,
    THETA_SKEWNESS,

    ALPHA_MAXIMUM,
    ALPHA_KURTOSIS,
    ALPHA_STANDARD_DEVIATION,
    ALPHA_SKEWNESS,

    BETA_MAXIMUM,
    BETA_KURTOSIS,
    BETA_STANDARD_DEVIATION,
    BETA_SKEWNESS,

    GAMMA_MAXIMUM,
    GAMMA_KURTOSIS,
    GAMMA_STANDARD_DEVIATION,
    GAMMA_SKEWNESS,

    ZERO_PADDING,
    ONE_SIDED_SPECTRUM,

    DELTA_RATIO,
    DELTA_POWER,
    LOG_DELTA_POWER,
    NORMALIZED_DELTA_POWER,

     THETA_RATIO,
     THETA_POWER,
     LOG_THETA_POWER,
     NORMALIZED_THETA_POWER,

     ALPHA_RATIO,
     ALPHA_POWER,
     LOG_ALPHA_POWER,
     NORMALIZED_ALPHA_POWER,

     BETA_RATIO,
     BETA_POWER,
     LOG_BETA_POWER,
     NORMALIZED_BETA_POWER,

    GAMMA_RATIO,
    GAMMA_POWER,
    LOG_GAMMA_POWER,
    NORMALIZED_GAMMA_POWER,

    SPECTRAL_EDGE_FREQUENCY_80,
    SPECTRAL_EDGE_FREQUENCY_90,
    SPECTRAL_EDGE_FREQUENCY_95,

    FREQUENCY_FILTERED_BAND_ENERGIES,
    RELATIVE_SPECTRAL_DIFFERENCE,
    SN_RATIO,
    POWER_SPECTRUM_MOMENTS,
    MODIFIED_MEDIAN_FREQUENCY,
    MODIFIED_MEAN_FREQUENCY,
    SPECTRAL_ENTROPY

}
