package model;

import android.support.annotation.Keep;
import android.support.annotation.NonNull;

import features.MelomindExerciseType;
import core.recording.metadata.DataSource;

/**
 * Created by manon on 19/10/16.
 */

/**
 * Class for informations about a new recording. It has a unique id, which is generated by the application then sent
 * to the server in the JSON file.
 * Id is unique for an acquisition session (ie calibration + session for melomind)
 * It also has a recordingType variable which indicates the global settings of this session
 */
@Keep
public class RecordInfo {
    private String recordId;
    private  RecordingType recordingType;

    @Keep
    public enum RecordType {
        CALIBRATION,
        SESSION,
        RAWDATA,
        STUDY
    }

    public RecordInfo(){}

    public RecordInfo(@NonNull String recordId){
        this.recordId = recordId;
        this.recordingType = new RecordingType();
    }

    public RecordInfo(@NonNull String recordId, @NonNull RecordingType recordingType){
        this.recordId = recordId;
        this.recordingType = recordingType;
    }

    public String getRecordId() {
        return recordId;
    }

    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    public RecordingType getRecordingType() {
        return recordingType;
    }

    public void setRecordingType(RecordingType recordingType) {
        this.recordingType = recordingType;
    }

    /**
     * Inner class for recording type.
     */
    public class RecordingType{
        private RecordType recordType;
        private String spVersion;
        private DataSource source;
        private MelomindExerciseType exerciseType;

        public RecordingType(){

        }

        public RecordingType(@NonNull RecordType recordType, @NonNull String spVersion, @NonNull DataSource dataSource, @NonNull MelomindExerciseType exerciseType){
            this.exerciseType = exerciseType;
            this.source = dataSource;
            this.spVersion = spVersion;
            this.recordType = recordType;
        }

        public RecordType getRecordType() {
            return recordType;
        }

        public void setRecordType(RecordType recordType) {
            this.recordType = recordType;
        }

        public String getSPVersion() {
            return spVersion;
        }

        public void setSPVersion(String SPVersion) {
            this.spVersion = SPVersion;
        }

        public DataSource getSource() {
            return source;
        }

        public void setSource(DataSource source) {
            this.source = source;
        }

        public MelomindExerciseType getExerciseType() {
            return exerciseType;
        }

        public void setExerciseType(MelomindExerciseType exerciseType) {
            this.exerciseType = exerciseType;
        }

    }

}




